workspace/config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  get 'employee_dashboard/index'

  get 'sessions/create'

  get 'sessions/destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

  get 'home/index'
  resources :admins
  resources :companies
  resources :admin_users
  resources :employees
  resources :admin_assets
  resources :messages
  resources :newsletters
  get 'messages/archive/:id' => 'messages#archive'
  get 'messages/unarchive/:id' => 'messages#unarchive'
  get 'messages/to_employee/:id' => 'messages#to_employee'
  post 'messages/send_msg/:id' => 'messages#send_msg'
  get 'home/password_change' => 'home#password_change'
  post 'admins/search_employee' => 'admins#search_employee'
  post 'employee_dashboard/search_employee' => 'employee_dashboard#search_employee'
  get 'admins/edit_password/:id' => 'admins#edit_password'
  patch 'admins/update_password/:id' => 'admins#update_password'
  get 'employee_dashboard/profile/:id' => 'employee_dashboard#profile'
  get 'employee_dashboard/show_asset/:id' => 'employee_dashboard#show_asset'
  get 'employee_dashboard/employee_asset' => 'employee_dashboard#employee_asset'
  get 'employee_dashboard/edit/:id' => 'employee_dashboard#edit'
  patch 'employee_dashboard/update/:id' => 'employee_dashboard#update'
  get 'employees/compose_mail/:id' => 'employees#compose_mail'
  post 'employees/send_mail/:id' => 'employees#send_mail'
  devise_for :users 
  

  root 'home#index'
  
  mount Resque::Server.new, at: "/resque"
  

end

workspace/app/models/asset.rb
class Asset < ActiveRecord::Base
	validates :name, :asset_category, :asset_type, presence: true
end

workspace/app/models/asset_category.rb
class AssetCategory < ActiveRecord::Base
end

workspace/app/models/client.rb
class Client < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |client|
      client.provider = auth.provider
      client.uid = auth.uid
      client.name = auth.info.name
      client.email = auth.info.email
      client.oauth_token = auth.credentials.token
      client.oauth_expires_at = Time.at(auth.credentials.expires_at)
      client.save!
    end
  end
end

workspace/app/models/company.rb
class Company < ActiveRecord::Base
end

workspace/app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :email, :name, :date_of_joining, :employment_status, presence: true
	validates :email, uniqueness: true
end

workspace/app/models/message.rb
class Message < ActiveRecord::Base
end

workspace/app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	serialize :sent_to, Array 
end

workspace/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

workspace/app/controllers/admin_assets_controller.rb
class AdminAssetsController < ApplicationController
	def index
		@admin_assets = Asset.all
	end
	def show
		@admin_asset = Asset.find(params[:id])
	end
	def new
		@admin_asset = Asset.new

	end
	def edit
		@admin_asset = Asset.find(params[:id])
	end
	def create
		ac= AssetCategory.where(asset_category: params[:asset][:asset_category], asset_type: params[:asset][:asset_type]).first
		l_asset= Asset.where(asset_category: params[:asset][:asset_category], asset_type: params[:asset][:asset_type]).last
		if ac.nil?
			cat = AssetCategory.where(asset_category: params[:asset][:asset_category]).first
			new_a_c= AssetCategory.new
			new_a_c.asset_category = params[:asset][:asset_category]
			new_a_c.asset_type= params[:asset][:asset_type]
			new_a_c.type_id =  1

			
			if cat.nil?
				last_cat=AssetCategory.order("category_id").last

				if last_cat.nil?
					new_a_c.category_id=1
				else

					new_a_c.category_id=(last_cat.category_id+1)
				end
			else

				new_a_c.category_id=cat.category_id
			end
			new_a_c.asset_category_id= (new_a_c.category_id*10) + new_a_c.type_id
			new_a_c.save
			ac_id=new_a_c.asset_category_id
			
		else 
			ac_id=ac.asset_category_id
		end
		
		if l_asset.nil? 
			
			calc = ac_id.to_i*1000
			
		else
			calc= l_asset.asset_id
		end
		calc=calc.to_i+1

		@admin_asset = Asset.new(params.require('asset').permit(:name, :asset_type, :asset_category, :specification, :assigned_to))
		@admin_asset.assigned_to = 0
		@admin_asset.asset_id= calc
		if @admin_asset.save
			
			redirect_to admin_asset_path(@admin_asset)
		else
			
			render 'new'
		end
	end
	def update
		@admin_asset = Asset.find(params[:id])
		if @admin_asset.update(params.require('asset').permit(:name, :asset_type, :asset_category, :specification, :assigned_to))
			redirect_to admin_asset_path(@admin_asset)
		else
			render 'edit'
		end
	end
	def destroy
		@admin_asset = Asset.find(params[:id])
		@admin_asset.destroy
		redirect_to admin_assets_path
	end
end

workspace/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
	end
	def show
		redirect_to admins_path
	end
	def edit
		@user=User.find(params[:id])
	end
	def update	
		@user=User.find(params[:id])
		if @user.update(params.require(:user).permit(:email, :name))
			redirect_to admins_path
		else 
			render 'edit'
		end
		
	end
	def edit_password
		@user=User.find(params[:id])
	end
	def update_password
		@user=User.find(params[:id])
		if @user.update(params.require(:user).permit(:password, :password_confirmation))		
			redirect_to home_password_change_path
		else 
			render 'edit_password'
		end
	end
	def search_employee
		@flag = 0
	end

end

workspace/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def password_change
  end
end

workspace/app/helpers/admin_assets_helper.rb
module AdminAssetsHelper
end

workspace/app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

workspace/app/helpers/admins_helper.rb
module AdminsHelper
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/assets_helper.rb
module AssetsHelper
end

workspace/app/helpers/companies_helper.rb
module CompaniesHelper
end

workspace/app/helpers/employees_helper.rb
module EmployeesHelper
end

workspace/app/helpers/home_helper.rb
module HomeHelper
end

workspace/app/helpers/messages_helper.rb
module MessagesHelper
end

workspace/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

workspace/app/helpers/sessions_helper.rb
module SessionsHelper
end

workspace/app/views/admin_assets/_form.html.erb
<%= form_for @admin_asset, url: admin_assets_path do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :asset_category %>
		<%= f.text_field :asset_category %>
	</p> 
	<p>
		<%= f.label :asset_type %>
		<%= f.text_field :asset_type %>
	</p>
	<p>
		<%= f.label :specification %>
		<%= f.text_field :specification %>
	</p>
	<p>
		<%= f.submit %>

	</p>
<% end %>
<%= link_to 'Back', admin_assets_path %>

workspace/app/views/admin_assets/edit.html.erb
<h3> Edit Asset </h3>
<%= form_for @admin_asset, url: admin_asset_path(@admin_asset) do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :asset_category %>
		<%= f.text_field :asset_category %>
	</p>
	<p>
		<%= f.label :asset_type %>
		<%= f.text_field :asset_type %>

	</p>
	<p>
		<%= f.label :specification %>
		<%= f.text_field :specification %>
	</p>
	<p>
		<%= f.label :assigned_to %>
		<%= f.text_field :assigned_to %>
		(Enter valid employee ID)
	</p>
	<p>
		<%= f.submit %>

	</p>
<% end %>
<%= link_to 'Back', admin_asset_path(@admin_asset) %>

workspace/app/views/admin_assets/index.html.erb
<h4>Assets </h4>
	<table>
		<tr>
			<th>Asset name</th>
			<th>Asset ID</th>
		</tr>
	<% @admin_assets.each do |asset| %>
		<tr>
			<td><%= asset.name %></td>
			<td><%= asset.asset_id %></td>
			<td><%= link_to 'View',  admin_asset_path(asset.id) %>|</td>
			<td><%= link_to 'Edit',  edit_admin_asset_path(asset.id) %>|</td>
			<td><%= link_to 'Delete', admin_asset_path(asset.id) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	 <% end %>
	</table>
<br/>
<%= link_to 'Create Asset', new_admin_asset_path %> |
<%= link_to 'Back', admins_path %>

workspace/app/views/admin_assets/new.html.erb
<h3> Create Asset </h3>
<%= render 'form' %>

workspace/app/views/admin_assets/show.html.erb
<h2><%= @admin_asset.name %></h2>
<h3>Asset Details </h3>
<ul>
	<li>ID:   <%= @admin_asset.asset_id %></li>
	<li><%= @admin_asset.asset_category %></li>
	<li><%= @admin_asset.asset_type %></li>
	<li><%= @admin_asset.specification %></li>
	<li>
		<% if @admin_asset.assigned_to == 0%>
			Un-assigned
		<% else %>
			<%= link_to Employee.find(@admin_asset.assigned_to).name , employee_path(@admin_asset.assigned_to) %>
		<% end %>
	</li>
</ul>
	
<%= link_to 'Edit',  edit_admin_asset_path(@admin_asset) %>|
<%= link_to 'Delete', admin_asset_path(@admin_asset) , method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Back', admin_assets_path %>