workspace/config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  get 'employee_dashboard/index'

  get 'sessions/create'

  get 'sessions/destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

  get 'home/index'
  resources :admins
  resources :companies
  resources :admin_users
  resources :employees
  resources :admin_assets
  resources :messages
  resources :newsletters
  get 'messages/archive/:id' => 'messages#archive'
  get 'messages/unarchive/:id' => 'messages#unarchive'
  get 'messages/to_employee/:id' => 'messages#to_employee'
  post 'messages/send_msg/:id' => 'messages#send_msg'
  get 'home/password_change' => 'home#password_change'
  post 'admins/search_employee' => 'admins#search_employee'
  post 'employee_dashboard/search_employee' => 'employee_dashboard#search_employee'
  get 'admins/edit_password/:id' => 'admins#edit_password'
  patch 'admins/update_password/:id' => 'admins#update_password'
  get 'employee_dashboard/profile/:id' => 'employee_dashboard#profile'
  get 'employee_dashboard/show_asset/:id' => 'employee_dashboard#show_asset'
  get 'employee_dashboard/employee_asset' => 'employee_dashboard#employee_asset'
  get 'employee_dashboard/edit/:id' => 'employee_dashboard#edit'
  patch 'employee_dashboard/update/:id' => 'employee_dashboard#update'
  get 'employees/compose_mail/:id' => 'employees#compose_mail'
  post 'employees/send_mail/:id' => 'employees#send_mail'
  devise_for :users 
  

  root 'home#index'
  
  mount Resque::Server.new, at: "/resque"
  

end

workspace/app/models/asset.rb
class Asset < ActiveRecord::Base
	validates :name, :asset_category, :asset_type, presence: true
end

workspace/app/models/asset_category.rb
class AssetCategory < ActiveRecord::Base
end

workspace/app/models/client.rb
class Client < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |client|
      client.provider = auth.provider
      client.uid = auth.uid
      client.name = auth.info.name
      client.email = auth.info.email
      client.oauth_token = auth.credentials.token
      client.oauth_expires_at = Time.at(auth.credentials.expires_at)
      client.save!
    end
  end
end

workspace/app/models/company.rb
class Company < ActiveRecord::Base
end

workspace/app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :email, :name, :date_of_joining, :employment_status, presence: true
	validates :email, uniqueness: true
end

workspace/app/models/message.rb
class Message < ActiveRecord::Base
end

workspace/app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	serialize :sent_to, Array 
end

workspace/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

workspace/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def password_change
  end
end

workspace/app/helpers/admin_assets_helper.rb
module AdminAssetsHelper
end

workspace/app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

workspace/app/helpers/admins_helper.rb
module AdminsHelper
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/assets_helper.rb
module AssetsHelper
end

workspace/app/helpers/companies_helper.rb
module CompaniesHelper
end

workspace/app/helpers/employees_helper.rb
module EmployeesHelper
end

workspace/app/helpers/home_helper.rb
module HomeHelper
end

workspace/app/helpers/messages_helper.rb
module MessagesHelper
end

workspace/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

workspace/app/helpers/sessions_helper.rb
module SessionsHelper
end

workspace/app/views/admins/edit.html.erb
<h2>Edit Admin</h2>

<%= form_for(:user, url: admin_path, method: 'patch') do |f| %>
  

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>
<%= link_to 'Back', admins_path %>

workspace/app/views/admins/edit_password.html.erb
<h2>Change Password</h2>

<%= form_for(:user, url: "/admins/update_password/#{current_user.id}", method: 'patch') do |f| %>
  

  

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>
<%= link_to 'Back', admins_path %>

workspace/app/views/admins/index.html.erb
<h1>Admin</h1>
<%= link_to 'Company Management', companies_path %> | 
<% if current_user.role == 'admin'%>
	<%= link_to 'User management',  admin_users_path%> | 
	<%= link_to 'Employee management', employees_path %> | 
<% else %>
	<%= link_to 'Employees',employees_path%> |
<% end %>
<%= link_to 'Asset Management', admin_assets_path %>
<br/>
<% if current_user.role == 'admin'%>
	<%= link_to 'Edit Admin', edit_admin_path(current_user.id) %>
	<br/>	
<% end %>
Search for employees:
<%=form_for :employee , url: admins_search_employee_path, method:  "post" do |f| %>
	<%=f.search_field :search_employee %>
<% end %>

<br/>
<%= link_to 'Change Password', "/admins/edit_password/#{current_user.id}" %>
<br/>
<% if current_user.role == 'admin'%>
	<%= link_to 'Messages', messages_path %>
	<%= link_to 'Newsletters', newsletters_path %>
<% end %>

workspace/app/views/admins/search_employee.html.erb
<h3>Search Results</h3>

<% Employee.where("name LIKE ? OR email LIKE ? OR id LIKE ? OR section LIKE ? ","%#{params[:employee][:search_employee]}%","%#{params[:employee][:search_employee]}%","%#{params[:employee][:search_employee]}%","%#{params[:employee][:search_employee]}%").find_each do |e| %>
						
	<%= link_to e.name, employee_path(e) %>					
	<% @flag+=1 %>	
	<br/>
<% end %>

<% if @flag==0 %>					
	<h4> No matches found!</h4>
<% end %>
<br/>
<%= link_to 'back' , admins_path %>

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body style= 'margin-right:30px; margin-left:20px;'>

	<nav style= "text-align:right;">
		<% if current_user %>
			<%= link_to 'log out', destroy_user_session_path, method: 'delete' %>
		<% else %>
	      <% if current_employee %>
	        <% unless Employee.find_by_email(current_employee.email).nil? %>
	        	<%= link_to "Sign out", signout_path, id: "sign_out" %>
	        <% else %>
	        	Employee doesnt exists!!!
	      	<% end %>
	      <% end %>
	     <% end %>
    </nav>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>