workspace/config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  get 'employee_dashboard/index'

  get 'sessions/create'

  get 'sessions/destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

  get 'home/index'
  resources :admins
  resources :companies
  resources :admin_users
  resources :employees
  resources :admin_assets
  resources :messages
  resources :newsletters
  get 'messages/archive/:id' => 'messages#archive'
  get 'messages/unarchive/:id' => 'messages#unarchive'
  get 'messages/to_employee/:id' => 'messages#to_employee'
  post 'messages/send_msg/:id' => 'messages#send_msg'
  get 'home/password_change' => 'home#password_change'
  post 'admins/search_employee' => 'admins#search_employee'
  post 'employee_dashboard/search_employee' => 'employee_dashboard#search_employee'
  get 'admins/edit_password/:id' => 'admins#edit_password'
  patch 'admins/update_password/:id' => 'admins#update_password'
  get 'employee_dashboard/profile/:id' => 'employee_dashboard#profile'
  get 'employee_dashboard/show_asset/:id' => 'employee_dashboard#show_asset'
  get 'employee_dashboard/employee_asset' => 'employee_dashboard#employee_asset'
  get 'employee_dashboard/edit/:id' => 'employee_dashboard#edit'
  patch 'employee_dashboard/update/:id' => 'employee_dashboard#update'
  get 'employees/compose_mail/:id' => 'employees#compose_mail'
  post 'employees/send_mail/:id' => 'employees#send_mail'
  devise_for :users 
  

  root 'home#index'
  
  mount Resque::Server.new, at: "/resque"
  

end

workspace/app/models/asset.rb
class Asset < ActiveRecord::Base
	validates :name, :asset_category, :asset_type, presence: true
end

workspace/app/models/asset_category.rb
class AssetCategory < ActiveRecord::Base
end

workspace/app/models/client.rb
class Client < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |client|
      client.provider = auth.provider
      client.uid = auth.uid
      client.name = auth.info.name
      client.email = auth.info.email
      client.oauth_token = auth.credentials.token
      client.oauth_expires_at = Time.at(auth.credentials.expires_at)
      client.save!
    end
  end
end

workspace/app/models/company.rb
class Company < ActiveRecord::Base
end

workspace/app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :email, :name, :date_of_joining, :employment_status, presence: true
	validates :email, uniqueness: true
end

workspace/app/models/message.rb
class Message < ActiveRecord::Base
end

workspace/app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	serialize :sent_to, Array 
end

workspace/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

workspace/app/controllers/employee_dashboard_controller.rb
class EmployeeDashboardController < ApplicationController
  def index
	end
  def profile
  end
  def search_employee
  	@flag = 0
  end
  def employee_asset
  end
  def show_asset
  	@asset= Asset.find(params[:id])
  end
  def edit
  	@employee = Employee.find_by_email(current_employee.email)
  end
  def update
  	@employee = Employee.find_by_email(current_employee.email)
  	if @employee.update(params.require(:employee).permit(:address, :date_of_birth, :mobile_no, :bank_account_details, :passport_details, :pancard_details, :qualifications, :adhar_card_details))
  		redirect_to "/employee_dashboard/profile/#{@employee.id}"
  	else
  		render 'edit'
  	end
  end
end

workspace/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def password_change
  end
end

workspace/app/helpers/admin_assets_helper.rb
module AdminAssetsHelper
end

workspace/app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

workspace/app/helpers/admins_helper.rb
module AdminsHelper
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/assets_helper.rb
module AssetsHelper
end

workspace/app/helpers/companies_helper.rb
module CompaniesHelper
end

workspace/app/helpers/employee_dashboard_helper.rb
module EmployeeDashboardHelper
end

workspace/app/helpers/employees_helper.rb
module EmployeesHelper
end

workspace/app/helpers/home_helper.rb
module HomeHelper
end

workspace/app/helpers/messages_helper.rb
module MessagesHelper
end

workspace/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

workspace/app/helpers/sessions_helper.rb
module SessionsHelper
end

workspace/app/views/employee_dashboard/edit.html.erb
<h2>Edit Employee</h2>

<%= form_for @employee, {url: "/employee_dashboard/update/#{@employee.id}", method: 'patch'} do |f| %>
<p>
Address:<br/>
<%= f.text_field :address %>
</p>
<p>
Phone Number:<br/>
<%= f.text_field :mobile_no %>
</p>


<p>
Date of Birth:<br/>
<%= f.date_field :date_of_birth %>
</p>
<p>
Bank Account Details:<br/>
<%= f.text_field :bank_account_details %>
</p>
<p>
Pancard Details:<br/>
<%= f.text_field :pancard_details %>
</p>
<p>
passport Details:<br/>
<%= f.text_field :passport_details %>
</p>
<p>
Adhar Card Details:<br/>
<%= f.text_field :adhar_card_details %>
</p>

<p>
Qualifications:<br/>
<%= f.text_field :qualifications %>
</p>
<br/>
<p><%= f.submit %></p>
<% end %>
<%= link_to 'Back', employees_path %>

workspace/app/views/employee_dashboard/employee_asset.html.erb
<h3>worXpace</h3>
<h4>Assets</h4>
<% employee_id = Employee.find_by_email(current_employee.email).id %>
<% Asset.where(assigned_to: employee_id).find_each do |asset|%>
	<%= link_to asset.name,  "/employee_dashboard/show_asset/#{asset.id}" %>
<% end %>
<br/><br/>
<%= link_to 'Back', employee_dashboard_index_path %>

workspace/app/views/employee_dashboard/index.html.erb
<% employee = Employee.find_by_email(current_employee.email)%>

<h3>worXpace</h3>
<%= link_to "Profile", "/employee_dashboard/profile/#{employee.id}" %><br/>
Search for employees:
<%=form_for :employee , url: employee_dashboard_search_employee_path, method:  "post" do |f| %>
	<%=f.search_field :search_employee %>
<% end %>
<br/>
<br/>

<%= link_to "Assets", employee_dashboard_employee_asset_path %>
<%= link_to "Messages", messages_path %>

workspace/app/views/employee_dashboard/profile.html.erb
<% employee= Employee.find(params[:id]) %>
<h3>worXpace</h3>
<h3><%= employee.name%></h3>
<h4>Employee Details</h4>
<table>
	<tr>
		<td>Employee ID</td>
		<th><%= employee.id%></th>
	</tr>
	<tr>
		<td>email ID</td>
		<th><%= employee.email%></th>
	</tr>
	</tr>
	<tr>
		<td>Phone Number</td>
		<th><%= employee.mobile_no%></th>
	</tr>
	</tr>

	</tr>
	<tr>
		<td>Date of Birth</td>
		<th><%= employee.date_of_birth%></th>
	</tr>

	</tr>
	<tr>
		<td>Employment Status</td>
		<th><%= employee.employment_status%></th>
	</tr>
	</tr>
	<tr>
		<td>Section</td>
		<th><%= employee.section%></th>
	</tr>
	</tr>
	<% if current_employee.email == employee.email %>
		<tr>
			<td>Address</td>
			<th><%= employee.address%></th>
		</tr>
		</tr>
		<tr>
			<td>Date of Employment Commenced</td>
			<th><%= employee.date_of_joining%></th>
		</tr>
	

		<tr>
			<td>Bank Account Details</td>
			<th><%= employee.bank_account_details%></th>
		</tr>
		</tr>
		<tr>
			<td>Adhar Card Details</td>
			<th><%= employee.adhar_card_details%></th>
		</tr>
		</tr>
		<tr>
			<td>Pan Card Details</td>
			<th><%= employee.pancard_details%></th>
		</tr>
		</tr>
		<tr>
			<td>Passport Details</td>
			<th><%= employee.passport_details%></th>
		</tr>
		</tr>
		<tr>
			<td>Qualifications</td>
			<th><%= employee.qualifications%></th>
		</tr>
		</tr>
	<% end %>
</table>
<% if current_employee.email == employee.email %>
	<%= link_to 'Edit Profile',  "/employee_dashboard/edit/#{employee.id}" %>
<% else %>
	<h4>Assets</h4>
	<% Asset.where(assigned_to: employee.id).find_each do |asset|%>
		<%= link_to asset.name,  "/employee_dashboard/show_asset/#{asset.id}" %>
	<% end %>
	<br/>
<% end %>
<br/>
<%= link_to 'Back', employee_dashboard_index_path %>

workspace/app/views/employee_dashboard/search_employee.html.erb
<h3>Search Results</h3>

<% Employee.where("name LIKE ? OR email LIKE ? OR id LIKE ? OR section LIKE ? ","%#{params[:employee][:search_employee]}%","%#{params[:employee][:search_employee]}%","%#{params[:employee][:search_employee]}%","%#{params[:employee][:search_employee]}%").find_each do |e| %>
						
	<%= link_to e.name, "/employee_dashboard/profile/#{e.id}" %>					
	<% @flag+=1 %>	
	<br/>
<% end %>

<% if @flag==0 %>					
	<h4> No matches found!</h4>
<% end %>
<br/>
<%= link_to 'back' , employee_dashboard_index_path %>

workspace/app/views/employee_dashboard/show_asset.html.erb
<h2><%= @asset.name %></h2>
<h3>Asset Details </h3>
<ul>
	<li>ID:   <%= @asset.asset_id %></li>
	<li><%= @asset.asset_category %></li>
	<li><%= @asset.asset_type %></li>
	<li><%= @asset.specification %></li>
	
</ul>
	

<%= link_to 'Back', employee_dashboard_index_path %>