workspace/config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  get 'employee_dashboard/index'

  get 'sessions/create'

  get 'sessions/destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

  get 'home/index'
  resources :admins
  resources :companies
  resources :admin_users
  resources :employees
  resources :admin_assets
  resources :messages
  resources :newsletters
  get 'messages/archive/:id' => 'messages#archive'
  get 'messages/unarchive/:id' => 'messages#unarchive'
  get 'messages/to_employee/:id' => 'messages#to_employee'
  post 'messages/send_msg/:id' => 'messages#send_msg'
  get 'home/password_change' => 'home#password_change'
  post 'admins/search_employee' => 'admins#search_employee'
  post 'employee_dashboard/search_employee' => 'employee_dashboard#search_employee'
  get 'admins/edit_password/:id' => 'admins#edit_password'
  patch 'admins/update_password/:id' => 'admins#update_password'
  get 'employee_dashboard/profile/:id' => 'employee_dashboard#profile'
  get 'employee_dashboard/show_asset/:id' => 'employee_dashboard#show_asset'
  get 'employee_dashboard/employee_asset' => 'employee_dashboard#employee_asset'
  get 'employee_dashboard/edit/:id' => 'employee_dashboard#edit'
  patch 'employee_dashboard/update/:id' => 'employee_dashboard#update'
  get 'employees/compose_mail/:id' => 'employees#compose_mail'
  post 'employees/send_mail/:id' => 'employees#send_mail'
  devise_for :users 
  

  root 'home#index'
  
  mount Resque::Server.new, at: "/resque"
  

end

workspace/app/models/asset.rb
class Asset < ActiveRecord::Base
	validates :name, :asset_category, :asset_type, presence: true
end

workspace/app/models/asset_category.rb
class AssetCategory < ActiveRecord::Base
end

workspace/app/models/client.rb
class Client < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |client|
      client.provider = auth.provider
      client.uid = auth.uid
      client.name = auth.info.name
      client.email = auth.info.email
      client.oauth_token = auth.credentials.token
      client.oauth_expires_at = Time.at(auth.credentials.expires_at)
      client.save!
    end
  end
end

workspace/app/models/company.rb
class Company < ActiveRecord::Base
end

workspace/app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :email, :name, :date_of_joining, :employment_status, presence: true
	validates :email, uniqueness: true
end

workspace/app/models/message.rb
class Message < ActiveRecord::Base
end

workspace/app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	serialize :sent_to, Array 
end

workspace/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

workspace/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
	end
	def show
		redirect_to admins_path
	end
	def edit
		@user=User.find(params[:id])
	end
	def update	
		@user=User.find(params[:id])
		if @user.update(params.require(:user).permit(:email, :name))
			redirect_to admins_path
		else 
			render 'edit'
		end
		
	end
	def edit_password
		@user=User.find(params[:id])
	end
	def update_password
		@user=User.find(params[:id])
		if @user.update(params.require(:user).permit(:password, :password_confirmation))		
			redirect_to home_password_change_path
		else 
			render 'edit_password'
		end
	end
	def search_employee
		@flag = 0
	end

end

workspace/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def password_change
  end
end

workspace/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
		Message.where(message: 'deleted', message_copy: 'deleted').find_each do |m|
			m.destroy
		end

	end
	def new 
		@message = Message.new
	end
	def create
		@message = Message.new
		@message.message= params[:message][:message]
		@message.message_copy= params[:message][:message]
		if current_employee
			@message.sender_id = Employee.find_by_email(current_employee.email).id
			@message.reciever_id = 1
		else
			@message.sender_id = 1
			@message.reciever_id = params[:message][:reciever_id]
		end
		@message.archive = 0
		if @message.save
			redirect_to messages_path
		else
			render 'message'
		end
	end
	def show
		@message = Message.find(params[:id])
	end
	def archive
		@message = Message.find(params[:id])
		@message.archive = 1
		if	@message.save
			redirect_to messages_path
		else
			admins_path
		end
		
	end
	def unarchive
		@message = Message.find(params[:id])
		@message.archive = 0
		if	@message.save
			redirect_to messages_path
		else
			admins_path
		end
		
	end

	def destroy
		@message = Message.find(params[:id])
		if current_user
			@message.message = 'deleted'
			@message.save
			redirect_to messages_path
		elsif current_employee
			@message.message_copy = 'deleted'
			@message.save
			redirect_to messages_path
		end
	end
	def to_employee
		@employee = Employee.find(params[:id])
	end
	def send_msg
		@employee = Employee.find(params[:id])
		@message = Message.new
		@message.message= params[:message][:message]
		@message.message_copy= params[:message][:message]
		@message.sender_id = 1
		@message.reciever_id = @employee.id
		@message.archive = 0
		if @message.save
			redirect_to messages_path
		else
			render 'message'
		end

	end
end

workspace/app/helpers/admin_assets_helper.rb
module AdminAssetsHelper
end

workspace/app/helpers/admin_employees_helper.rb
module AdminEmployeesHelper
end

workspace/app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

workspace/app/helpers/admins_helper.rb
module AdminsHelper
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/assets_helper.rb
module AssetsHelper
end

workspace/app/helpers/companies_helper.rb
module CompaniesHelper
end

workspace/app/helpers/employees_helper.rb
module EmployeesHelper
end

workspace/app/helpers/home_helper.rb
module HomeHelper
end

workspace/app/helpers/messages_helper.rb
module MessagesHelper
end

workspace/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

workspace/app/helpers/sessions_helper.rb
module SessionsHelper
end

workspace/app/views/messages/index.html.erb
<h3>Messages</h3>
<% if current_employee %>
	Recieved Messages:<br/>
		
		<% if Message.where(reciever_id: Employee.find_by_email(current_employee.email).id).first.nil? %>
			<strong>No messages</strong>
		<% else %>
			<table>
				<tr>
					<th>Message</th>

				</tr>
				<% Message.where(reciever_id: Employee.find_by_email(current_employee.email).id).find_each do |m| %>
					<% if m.message_copy != "deleted" %>
						<tr>
							<td>					
								<%= m.message_copy%>
								<%= link_to 'delete', message_path(m.id), method: 'delete' %>
								
							</td>
						</tr>
					<% end %>
				<% end %>
			</table>

		<% end %>
	<br/>

	Sent Messages:<br/>
		
		<% if Message.where(sender_id: Employee.find_by_email(current_employee.email).id).first.nil? %>
			<strong>No messages</strong>
		<% else %>
			<table>
				<tr>
					<th>Message</th>

				</tr>
				<% Message.where(sender_id: Employee.find_by_email(current_employee.email).id).find_each do |m| %>
					<% if m.message_copy != "deleted" %>
						<tr>
							<td>
							
								<%= m.message_copy%>
								<%= link_to 'delete', message_path(m.id), method: 'delete' %>
							
							</td>
						</tr>
					<% end %>
				<% end %>
			</table>

		<% end %>
	<br/>
	<%= link_to 'New Message', new_message_path %>|
	<%= link_to 'Back', employee_dashboard_index_path %>
<% else %>
	Recieved Messages:<br/>		
		<% if Message.where(reciever_id: current_user.id).first.nil? %>
			<strong>No messages</strong>
		<% else %>
			
			<table>
				<tr>
					<th>Message</th>
					<th>Sender</th>

				</tr>
				<% Message.where(reciever_id: current_user.id).find_each do |m| %>
					<% if m.message != "deleted" %>
						<tr>
							<td>							
								<%= link_to m.message, "/messages/archive/#{m.id}" %>
											
							</td>
							<td>
								<%= Employee.find(m.sender_id).name %>
							</td>
							<td><%= link_to 'reply', "/messages/to_employee/#{m.sender_id}" %>|</td>
							<td><%= link_to 'delete', message_path(m.id), method: 'delete' %></td>
						</tr>
					<% end %>
				<% end %>
			</table>

		<% end %>
	<br/>
	<br/>
	<br/>
	Sent Messages:<br/>
		
		<% if Message.where(sender_id: current_user.id).first.nil? %>
			<strong>No messages</strong>
		<% else %>
			<table>
				<tr>
					<th>Message</th>
					<th>Sent to:</th>

				</tr>
				<% Message.where(sender_id: current_user.id).find_each do |m| %>
					<% if m.message != "deleted" %>
						<tr>
							<td>
							
								<%= link_to m.message, "/messages/archive/#{m.id}"%>
								
							
							</td>
							<td>
								<%= Employee.find(m.reciever_id).name %>

							</td>
							<td><%= link_to 'delete', message_path(m.id), method: 'delete' %></td>
						</tr>
					<% end %>
				<% end %>
			</table>

		<% end %>
		<br/>
		<br/>
		<br/>
	Recieved Messages Archived:<br/>		
		<% if Message.where(reciever_id: current_user.id, archive: 1).first.nil? %>
			<strong>No messages</strong>
		<% else %>
			
			<table>
				<tr>
					<th>Message</th>
					<th>Sender</th>

				</tr>
				<% Message.where(reciever_id: current_user.id, archive: 1).find_each do |m| %>
					<% if m.message != "deleted" %>
						<tr>
							<td>							
								<%=  m.message %>
								<%= link_to 'delete', "/messages/unarchive/#{m.id}"%>			
							</td>
							<td>
								<%= Employee.find(m.sender_id).name %>
							</td>
							<td><%= link_to 'reply', "/messages/to_employee/#{m.sender_id}" %></td>
						</tr>
					<% end %>
				<% end %>
			</table>

		<% end %>
	<br/>
	<br/>
	<br/>
	Sent Messages Archived:<br/>
		
		<% if Message.where(sender_id: current_user.id, archive: 1).first.nil? %>
			<strong>No messages</strong>
		<% else %>
			<table>
				<tr>
					<th>Message</th>
					<th>Sent to:</th>

				</tr>
				<% Message.where(sender_id: current_user.id, archive: 1).find_each do |m| %>
					<% if m.message != "deleted" %>
						<tr>
							<td>
							
								<%=  m.message %>
								<%= link_to 'delete', "/messages/unarchive/#{m.id}"%>
								
							
							</td>
							<td>
								<%= Employee.find(m.reciever_id).name %>

							</td>
						
						</tr>
					<% end %>
				<% end %>
			</table>

		<% end %>

	<br/>
	<%= link_to 'New Message', new_message_path %>|
	<%= link_to 'Back', admins_path %>

<% end %>

workspace/app/views/messages/new.html.erb
<%= form_for @message, url: messages_path, method: 'post' do |f| %>
	<p>
		Message:<br/>
		<%= f.text_area :message %>
	</p>
	<% if current_user && current_user.role == 'admin'%>
		<p>
		Reciever ID:<br/>
		<%= f.text_field :reciever_id %>
		</p>
	<% end %>

	<p>
		<%= f.submit :send %>

	</p>

<% end %>
<%= link_to 'Back', messages_path %>

workspace/app/views/messages/to_employee.html.erb
<%= form_for :message, url: " /messages/send_msg/#{@employee.id}", method: 'post' do |f| %>
	<p>
		Message:<br/>
		<%= f.text_area :message %>
	</p>
	
	<p>
		<%= f.submit :send%>

	</p>

<% end %>
<%= link_to 'Back', messages_path %>